sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product ittn-017
env:
  global:
    -
      # LTD_AWS_ID
      secure: CSj4ePtj80WKcYdQKuDXT6IyHqDCabmHDKw1KDAWWGGVNo1Mw4gLEQzC8FbW14bGQWC/Ggu0jAZwsZFAT5jhZHrVuXwnn+JwBsVMTTgl1SGRHpJAFYxLwOWKu2lZfBjwG7obUCCOjSlm5jppNFrooenEMIE/54adoVsLM4kbaf6xYgSJZ9zyWyY4fp1SoTdFHPLJ4izDjNsLZsTO2m3LZ66N5JQFiLh/5snJgrvUXNzsZq0PbCFYXCiITIonF2xuXRsiUh+Zfp1Z/Gx4WynWaP4ICca5/Isr70wruR4lJFobhmT8CCUbhloMbJ5Vc9+xHegjZiez29jZ9yPGDmmoBm6hK5Vneipc8q2qDUCgmUP+KgPVWqAcGK7R/+7sX+Q9fC239wuUqkZe+aZCwC9zWpH2a2zyzZoSQKo09Ouq8AnkxT8bzJST2teMWjDFeIF8tBLW6nIHqJsu51OjynWj6m5rwxpB5wHWvVocacscyXo7jbYco9fmZTAhK3Uuo8cVbIx9rWtOhDWAx9ZTxak7Vkg3EPbAOLcEhhA2SsURT0oI9fRSZ5QEFq6/+Ywg1UaSqx4IQ1YNotb93A2pWtogTaOQSVVF7iHXi3F5jdaENqxxWpXWDhPmKed1nNXW5LoNXjFqfuhMbMD0zwapsav4ddkyJ5dc8WgI1y/cIpU24So=
    -
      # LTD_AWS_SECRET
      secure: OuFGVafRIdhUm9zAW4w3ch1QMC37PGhhJHWg33VEdzgKjc02zQWQ/DPCmyG14bwrUlwKlNHzyUMxQXXV+QndAaWc/kgKm+WFL/utRF5Yeezc7a4Osf6XzJURQ5pqPRCMTkN5sY0sNUuOg3PqmKrMl5Nok7JSyXHfvvUP3bZLNiufajq3IOfLYAAyLuSChegluyjDR8oZ4xPCzAoEs5NOMPU7xTKYWtbLYFwjip32kGmsvdg1Rh6nLCzneq7xoJHeU1Js4nNIucLifKrbyLcPu0GdstOTyRcxbJia1UaHsn48pXdag7H6aNXhks0a7TiGobHyRcHcyAutcYaKYnCA+aP1VzE5yhonXsBM4ecE1Q71Ki+bRes2B+oln8rpYRzyJ81+hgEBKIi2wSi+QZ9AFM7KcqGI04A6CyPu2rCK7e/3UKEloyEbrA4i9LRcDax/TmSD/xDXsC/HKkkO+u4kA4FcW7OZskp3QfjqaVeh4oVXAGbR4OtMgAFa2iKBo8FIevv/7p9k9NvCZ9BTv6UuBKVTwxL1lz/arnUvQMCqEBfwe5vvNmAl4R51DJpnVRkkod5cWtVegH1Cvrzje6VsaobgAOG4e7Jyyw8WDWbN4r3lb2PnB8gbl9J3ZMP0JPP1cwnTJ3ic2FKwfztxgDoWX3BA0Y9VMwZrqo1N8waly5g=
    -
      # LTD_USERNAME
      secure: dxqYihPvt1WTXeJN9+tYEwwzrkcGPQsbKwSy6hbUmVG1KllIhiAZ6twZXRKhGBw1n2u2YW5cwPc+FOlKxpTjYwOvqaBWAWdg+w/c2ZWcRiZib+x/sagyFKI3ksq3tqNkWXOh/+8K8zlhwCrTHS4URVubl3TfgWqsjyaEjeHW2RLeXLx20AxOZj5Bo7akjc8RGGU8Bu477JuiqWK/JKciCaRk9jbFD4OVysm3vgD2KKmwSl40TQWpFxKUgAe31ihNYBCEm1tyg1FYKXl7g9egTMJBGPcGyj1ZPqm3BXUKOHQsnb6X+n1JB5e3F0vsnOtYCkN20g/8yGVgOYeh+sy7goG7nzXoo1lmsVsl43hlXda3ZvZvh5enY5DETG8EUV4+Qj17TjTv+H0jPzLY66sd8w69VaBjlOhLEIqLUQGPfNM0F8ds8LygH8Eisuat2sfAJLdCDn2jc6cBCrKE7Z8wA3Cb6hFT8sTPBL17l2JBIFbsZdsuKRam/OV/y9/t8hAzAFGQh/oh0+XlwJpVHRJtt9BysMDEJAb0VlXG4q8Atdy6YKwZBijhFEkjOerZS8w1SW/xuPHaqWZw58GNbODqc7/qahO8Rz4KpgngEu2Mon2Pjhzxf/9Rptz3G5OdPAqEjlwXsSlAhqGya1X/Vq0YQ4t0m4L4DTw93uleFmwyzpM=
    -
      # LTD_PASSWORD
      secure: IqBVKWTiSVcwqSemdTkN6pWaLJCWjlkk3de4DM4flLO+bfg42jxcN0q9ugniamiPaLHS+fwmy32Pefw+dsEiF3lrRkqjxY54Iv1WAk+b/CiWCfybOrB1gLjvDAvFAnLzIzg9RmEPtpyfm0SP8rEwjii93jcGqZnh78AS09IEEcc3I1mC5w+I8XO/KVOTJ3nIRZFva9LfRx7jsQuVh2mZAxmjEphj/LjsXp0+y1u9cm8O0mDOj4HlU+pvu19IQne/MHlz9lPL28kjfhiYQjBcQgUs6BlkYp76c+4vVOMTEAHPA4NC/p2n8sP2h/ggw5su3WT4Z6tE72Rnt3hKfdYaW5ng/ir+LDIxP8YOobBbz8vOJBqMWuaC7ktp5gHtJIMEoer/IV137famXniol5yZhswBeiwx/37OLoFz+7+kTXTxuf5tsm+4Mqdb2MnZoQcV4a1MHIvsKMOuCs2nLnJIKHe3/TgQQKFraSnMowO9HW1FoCIdJmV7C7ccXimD/iwP/pC4pJLM8+pGC1zw0odoHISytrEPo73GW+xOFFDvRaxr365kG3TZQ9dhDYTsVSR6EzPEXq5pya01yew6UHgcWd7f63o0r5f8/uoUqjH/oWin5iRZdGLraxM2ov9gCHEeIwdVEITUJzOI1GPBA8fxTPzX8E/W53He3C2Pe4Tx4aQ=
